
version: "2"
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - "888:80"

  mysql:
    restart: always
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "docker" # TODO: Change this
      MYSQL_USER: "docker"
      MYSQL_PASS: "docker"
    volumes:
      - ~/db/mysql-autodatee_core:/var/lib/mysql
    ports:
      - "3307:3306"
