
version: '3'
services:
  php:
    restart: always
    image: yiisoftware/yii2-php:7.1-apache
    container_name: autodatee_core_yii
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - 888:80

  mysql:
    restart: always
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_DATABASE: default_schema
    volumes:
      - ~/db/mysql-autodatee_core:/var/lib/mysql
    ports:
      - 3307:3306

  phpmyadmin:
    restart: always
    image: phpmyadmin/phpmyadmin
    container_name: autodatee_core_phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3307
      PMA_ARBITRARY: 1
    ports:
      - 999:80
    links:
      - mysql
    depends_on:
      - mysql
